### ISSUE TITLE
TXNID too long (PaymentExpress_PxPay)

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-omnipay#142]
When a transaction ID is not provided, the md5-like hash identifier that is put in it's place is too long and is rejected by PxPay

```
  object(SimpleXMLElement)#1193 (2) {
    ["@attributes"]=>
    array(1) {
      ["valid"]=>
      string(1) "0"
    }
    ["URI"]=>
    string(14) "txnid too long"
  }
```

**Comment by bummzack** [comment]
Since you can pass the transaction-id easily as a parameter, this shouldn't be too much of a problem? Just provide a shorter ID?

I'm hesitant to change the default-behavior, just because it causes an easily solvable issue with one gateway. If you can't pass the transaction-ID as parameter, there's always the possibility to use extensions where you can pass in custom data according to your needs.

**Comment by ReeceA** [comment]
Yeah definitely, but out-of-the-box you should truncate to something shorter for plug-and-play reasons :) though ultimately this is your baby.

**Comment by bummzack** [comment]
Don't get me wrong. I appreciate you reported this. I'm just saying that we can't just change to a shorter ID, since this would probably fall under public-API according to SemVer. So the earliest we can implement this would be `3.0`. I'm marking this issue for 3.0. Ideally we would have somebody that looks at all the officially supported gatways and looks what kind of ID would be compatible with all of them.

**Comment by wilr** [comment]
See this extension to fix PXPay. @bummzack did we want to put these into core (like the SagePay one) or simply link to Gists?

```
<?php

use SilverStripe\Core\Extension;

/**
 * Fix request for PxPay
 *
 * SilverStripe\Omnipay\Service\PaymentService:
 *  extensions:
 *    - PxPayExtension
 */
class PxPayExtension extends Extension
{
    /**
     * @param array $gatewayData
     */
    public function onBeforePurchase(array &$gatewayData)
    {
        $this->fixTransactionId($gatewayData);
    }

    /**
     * @param array $gatewayData
     */
    public function onBeforeAuthorize(array &$gatewayData)
    {
        $this->fixTransactionId($gatewayData);
    }

    /**
     * @param array $gatewayData
     */
    public function onBeforeCompletePurchase(array &$gatewayData)
    {
        $this->fixTransactionId($gatewayData);
    }

    /**
     * @param array $gatewayData
     */
    public function onBeforeCompleteAuthorize(array &$gatewayData)
    {
        $this->fixTransactionId($gatewayData);
    }

    private function fixTransactionId(array &$gatewayData)
    {
        /** @var \Payment $payment */
        $payment = $this->owner->getPayment();

        if ($payment->Gateway == 'PaymentExpress_PxPay') {
            $gatewayData['transactionId'] = substr($gatewayData['transactionId'], 0, 16);
        }
    }
}
```

**Comment by bummzack** [comment]
Adding to core seems fine.

**Comment by hchokshi** [comment]
@wilr
`$gatewayData['transactionId'] = substr($gatewayData['transactionId'], 0, 16);`
While this fixes the transaction ID sent to `PxPay`, as far as I can tell it doesn't update the `Identifier` column in the database. This means the return to `PaymentGatewayController::index` will have an identifier (16 chars) which won't match anything in the database (all still 30 chars).

**Comment by wilr** [comment]
@hchokshi it doesn't update the database stored ID. If you want to match you could also hook into `updatePaymentFromRequest` on that method.
