### ISSUE TITLE
Package guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by mlewis-everley** [silverstripe/silverstripe-omnipay#167]
Just thought I would point out that I get this message from composer when requiring or updating silverstripe-omnipay:

`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

I am not 100% clear if this is coming from this module or omnipay itself however...

**Comment by stevie-mayhew** [comment]
Its from this package: https://github.com/silverstripe/silverstripe-omnipay/blob/master/composer.json#L12

**Comment by bummzack** [comment]
No, guzzle/guzzle is a dependency of the omnipay library itself. https://github.com/thephpleague/omnipay-common/blob/v2.5.1/composer.json#L31

I think this is due to PHP compatibility, omnipay 2.x has to be PHP 5.3 compatible, whereas guzzle >= 4 requires PHP 5.4 or newer.

This can only be fixed once omnipay hits 3.x
