### ISSUE TITLE
Simulating on-site payment with an iframe

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#17]
A trick to simulate an on-site payment form is to display the external payment form inside an iframe.

It would be good to provide either tools, or instructions on how to achieve this.

**Comment by jameshoward** [comment]
The only issue with spoofing on-site payments is the lack of SSL and green bar in the address bar. By redirecting to PayPal, for instance, the user gets reassured that they are on a secure and trusted site when entering their payment details.

Not saying that it shouldn't be built in to the module, just that it I would argue it would have to be a config option rather than the default behaviour.

**Comment by jedateach** [comment]
@jameshoward Yes, I agree with your concerns about not showing SSL/green in address bar.

Showing the gateway site within an iframe isn't planned to be the default behaviour, and yes should be enabled via config - perhaps on a per-gateway basis.

Adding a SSL cert to the merchant site might help alleviate the address bar concerns.

**Comment by bummzack** [comment]
I think this approach is destined to fail because of security standards. 
I'm closing this as an option.
