### ISSUE TITLE
Status not being set to 'Created' on SS 3.7

### ISSUE THREAD

**Issue by thats4shaw** [silverstripe/silverstripe-omnipay#205]
Stumbled across a weird bug when using this module which seems exclusive to SilverStripe 3.7.

When creating a new payment I was finding that the status was never been set to 'Created' or accessible in the following context. 

```
$payment = Payment::create()
        ->init("PxPayGateway", 100, "NZD")
        ->setSuccessUrl($this->Link('complete')."/".$donation->ID)
        ->setFailureUrl($this->Link()."?message=payment can
```

It would throw this error:
`[User Error] Uncaught SilverStripe\Omnipay\Exception\InvalidStateException: Cannot initiate a purchase with this payment. Status is not "Created"`

The status being set to 'Created' is crucial as the `init` method fires off to gateway, amount and currency setters which have checks to make sure the status is set to 'Created'.

To work around it I just manually set the status before calling the `init` method.

**Comment by mikeyc7m** [comment]
I have a similar issue, could be the same. I have no payments in my system but when i go to the payments section it throws an error:
`[User Warning] Missing default for localisation key SilverStripe\Omnipay\Model\Payment.STATUS_
GET /admin/payments/
Line 174 in /media/www/aroc/vendor/silverstripe/framework/src/i18n/i18n.php`

Pretty sure this is because the status default is missing, even if there aren't any payments!

**Comment by bummzack** [comment]
That's really odd, since there is a default value for `Status`. Has there been a change in framework that would no longer set the default values?

**Comment by mikeyc7m** [comment]
Maybe it's because the `$summary_fields` use PaymentStatus but the search context `getDefaultSearchContext()`  tries to extend Status. I think the search context needs to use PaymentStatus too?
